SET SERVEROUTPUT ON;
BEGIN
      DBMS_OUTPUT.PUT_LINE('HOLA HOLA HOLITA. ESTOY EMPEZANDO CON PLSQL');
END;

DECLARE
    A NUMBER;
    B NUMBER;
    C NUMBER;
BEGIN
    DBMS_OUTPUT.PUT_LINE('SUMANDO NUMERICOS');
    A:=&IntroduceNumero1;
    B:=&IntroduceNumero2;
    C:=A+B;
    DBMS_OUTPUT.PUT_LINE('LA SUMA ES '|| C);
END;

DECLARE
  A NUMBER;
  B NUMBER;
  MAYOR NUMBER;
BEGIN
  DBMS_OUTPUT.PUT_LINE('SUMANDO NUMERICOS VERSION 2.0');
  A:=&INTRODUCENUMERO1;
  B:=&INTRODUCENUMERO2;
  IF A>B THEN
    MAYOR:=A;
  ELSE
    MAYOR:=B;
  END IF;
  DBMS_OUTPUT.PUT_LINE('EL MAYOR ES '||MAYOR);
END;

CREATE OR REPLACE PROCEDURE ImprimirMensaje
IS
BEGIN
  DBMS_OUTPUT.PUT_LINE('hola hola holita, creando procedimientos en plsql');
END;

EXECUTE ImprimirMensaje;

CREATE OR REPLACE PROCEDURE Sumando2Numeros (A NUMBER, B NUMBER)
IS C NUMBER;
BEGIN
  DBMS_OUTPUT.PUT_LINE('HOLA HOLITA, VAMOS A SUMAR DOS NUMERITOS');
  C:=A+B;
  DBMS_OUTPUT.PUT_LINE('LA SUMA DE LOS NUMERITOS ES '||C);
END;

EXECUTE SUMANDO2NUMEROS (5,2);

CREATE OR REPLACE PROCEDURE mayoromenor (A NUMBER, B NUMBER)
IS MAYOR NUMBER;
BEGIN
  DBMS_OUTPUT.PUT_LINE('VAMOS A VER QUE NUMERICO ES MAYOR');
  IF A>B THEN
    MAYOR:=A;
  ELSE IF
    MAYOR:=B;
  END IF;
  DBMS_OUTPUT.PUT_LINE('EL MAYOR ES '||MAYOR);
END;

EXECUTE MAYOROMENOR (10,5);

CREATE OR REPLACE PROCEDURE holacaracola (A NUMBER:=0)
IS
BEGIN
  FOR A IN 0..3 LOOP
    DBMS_OUTPUT.PUT_LINE('HOLA HOLA CARA DE COLA');
  END LOOP;
END;

CREATE OR REPLACE PROCEDURE HOLOCARACOLO (A NUMBER:=0)
IS
BEGIN
  WHILE (A<=3) LOOP
    DBMS_OUTPUT.PUT_LINE('HOLO HOLO CARA DE COLO');
    A:=A+1;
  END LOOP;
END;

EXECUTE HOLOCARACOLO;

CREATE OR REPLACE PROCEDURE HOLACARACOLA2
IS A NUMBER:=0; B NUMBER:=0;
BEGIN
  WHILE (A<=3) LOOP
    DBMS_OUTPUT.PUT_LINE('FEDE NO TIENES RAZON');
    A:=A+1;
  END LOOP;
END;
EXECUTE HOLACARACOLA2;

DECLARE
  A NUMBER:=0;
BEGIN
  FOR A IN 0..10 LOOP
    HOLACARACOLA2;
  END LOOP;
END;