SET SERVEROUTPUT ON;
DECLARE
  TYPE NOMBRES IS VARRAY(5) OF VARCHAR2(10);
  NOM NOMBRES;
  TYPE EDADES IS VARRAY(5) OF INTEGER;
  EDAD EDADES;
  CONTADOR NUMBER;
  CONTADOR1 NUMBER;
BEGIN
  NOM:=NOMBRES('KEVIN','SANDRA','JORGE','DAVID','ALEX');
  EDAD:=EDADES(19,18,22,28,28);
  CONTADOR:=NOM.COUNT;
  FOR I IN 1..CONTADOR LOOP
    DBMS_OUTPUT.PUT_LINE(NOM(I)|| ' ' || EDAD(I));
  END LOOP;
END;

/* IMPRIMIR MAYORES DE 20*/
DECLARE
  TYPE NOMBRES IS VARRAY(5) OF VARCHAR2(10);
  NOM NOMBRES;
  TYPE EDADES IS VARRAY(5) OF INTEGER;
  EDAD EDADES;
  CONTADOR NUMBER;
  CONTADOR1 NUMBER;
BEGIN
  NOM:=NOMBRES('KEVIN','SANDRA','JORGE','DAVID','ALEX');
  EDAD:=EDADES(19,18,22,28,28);
  CONTADOR:=NOM.COUNT;
  FOR I IN 1..CONTADOR LOOP
    IF EDAD(I)>20 THEN
      DBMS_OUTPUT.PUT_LINE(NOM(I)|| ' ' || EDAD(I));
    END IF;
  END LOOP;
END;
/*APARTADO 1*/
DECLARE
  TYPE NOMBRES IS VARRAY(5) OF VARCHAR2(10);
  NOM NOMBRES;
  TYPE NOTAS IS VARRAY(5) OF INTEGER;
  NOTA NOTAS;
  CONTADOR NUMBER;
  CONTADOR1 NUMBER;
BEGIN
  NOM:=NOMBRES('KEVIN','SANDRA','JORGE','DAVID','ALEX');
  NOTA:=NOTAS(10,8,2,4,5);
  CONTADOR:=NOM.COUNT;
  FOR I IN 1..CONTADOR LOOP
    DBMS_OUTPUT.PUT_LINE(NOM(I)|| ' ' || NOTA(I));
  END LOOP;
END;
/*APARTADO 2*/
DECLARE
  TYPE NOMBRES IS VARRAY(5) OF VARCHAR2(10);
  NOM NOMBRES;
  TYPE NOTAS IS VARRAY(5) OF INTEGER;
  NOTA NOTAS;
  CONTADOR NUMBER;
  CONTADOR1 NUMBER;
BEGIN
  NOM:=NOMBRES('KEVIN','SANDRA','JORGE','DAVID','ALEX');
  NOTA:=NOTAS(10,8,2,4,5);
  CONTADOR:=NOM.COUNT;
  FOR I IN 1..CONTADOR LOOP
    IF MOD(I,2)!=0 THEN
      DBMS_OUTPUT.PUT_LINE(NOM(I)|| ', NOTA: ' ||NOTA(I));
    END IF;
  END LOOP;
END;
/*APARTADO 3*/
DECLARE
  TYPE NOTAS IS VARRAY(5) OF INTEGER;
  NOTA NOTAS;
  CONTADOR NUMBER;
BEGIN
  NOTA:=NOTAS(10,8,2,4,5);
  CONTADOR:=NOTA.COUNT;
  FOR I IN 1..CONTADOR LOOP
    DBMS_OUTPUT.PUT_LINE('NOTA'||I||': ' || NOTA(I));
  END LOOP;
END;
/*APARTADO 4*/
DECLARE
  TYPE NOTAS IS VARRAY(5) OF INTEGER;
  NOTA NOTAS;
  CONTADOR NUMBER;
BEGIN
  NOTA:=NOTAS(10,8,2,4,5);
  CONTADOR:=NOTA.COUNT;
  FOR I IN 1..CONTADOR LOOP
    IF NOTA(I)>=5 THEN
      DBMS_OUTPUT.PUT_LINE(NOTA(I));
    END IF;
  END LOOP;
END;
/*APARTADO 5*/
DECLARE
  TYPE NOMBRES IS VARRAY(5) OF VARCHAR2(10);
  NOM NOMBRES;
  TYPE NOTAS IS VARRAY(5) OF INTEGER;
  NOTA NOTAS;
  CONTADOR NUMBER;
  CONTADOR1 NUMBER;
BEGIN
  NOM:=NOMBRES('KEVIN','SANDRA','JORGE','DAVID','ALEX');
  NOTA:=NOTAS(10,8,2,4,5);
  CONTADOR:=NOM.COUNT;
  FOR I IN 1..CONTADOR LOOP
    DBMS_OUTPUT.PUT_LINE('ALUMNO: '||NOM(I)|| ', NOTA: ' || NOTA(I));
  END LOOP;
END;
/*APARTADO 6*/
DECLARE
  TYPE NOMBRES IS VARRAY(5) OF VARCHAR2(10);
  NOM NOMBRES;
  TYPE NOTAS IS VARRAY(5) OF INTEGER;
  NOTA NOTAS;
  CONTADOR NUMBER;
  CONTADOR1 NUMBER:=0;
BEGIN
  NOM:=NOMBRES('KEVIN','SANDRA','JORGE','DAVID','ALEX');
  NOTA:=NOTAS(10,8,2,4,5);
  CONTADOR:=NOM.COUNT;
  FOR I IN 1..CONTADOR LOOP
    IF NOTA(I)>=5 THEN 
      DBMS_OUTPUT.PUT_LINE('ALUMNO: '||NOM(I)|| ', NOTA: ' || NOTA(I));
      CONTADOR1:=CONTADOR1+1;
    END IF;
  END LOOP;
  DBMS_OUTPUT.PUT_LINE('HAN APROBADO: '|| CONTADOR1);
END;
/*APARTADO EXTRA*/
DECLARE
  TYPE NOMBRES IS VARRAY(5) OF VARCHAR2(10);
  NOM NOMBRES;
  TYPE NOTAS IS VARRAY(5) OF INTEGER;
  NOTA NOTAS;
  CONTADOR NUMBER;
  ALUMNO VARCHAR2(10);
  NOTAMAYOR INTEGER:=0;
BEGIN
  NOM:=NOMBRES('KEVIN','SANDRA','JORGE','DAVID','ALEX');
  NOTA:=NOTAS(9,8,1,4,5);
  CONTADOR:=NOM.COUNT;
  FOR I IN 1..CONTADOR LOOP
    IF NOTA(I)>=NOTAMAYOR THEN 
      NOTAMAYOR:=NOTA(I);
      ALUMNO:=NOM(I);
    END IF;
  END LOOP;
  DBMS_OUTPUT.PUT_LINE('LA MAYOR NOTA ES: '||NOTAMAYOR||' Y LA TIENE: '||ALUMNO);
END;